
ARCH_MK_PATH := arch/riscv/mk

.PHONY: qemu

include $(ARCH_MK_PATH)/arch-riscv.mk

include $(ARCH_MK_PATH)/source.mk

include $(ARCH_MK_PATH)/build.mk
include $(ARCH_MK_PATH)/images.mk
include $(ARCH_MK_PATH)/run.mk
