#ifndef MACHINE_H
#define MACHINE_H

#define KERNEL_VIRT_OFFSET 0xFFFFFFC000000000UL // Hight Address Offset
#define DRAM_BASE_LOW 0x80000000UL
#define DRAM_SIZE (128UL * 1024 * 1024)

#ifdef OPEN_SBI_BOOT
#define KERNEL_BASE_LOW 0x80200000UL
#else
#define KERNEL_BASE_LOW DRAM_BASE_LOW
#endif

#define PHYSTOP_LOW (DRAM_BASE_LOW + DRAM_SIZE)
#define KERNEL_BASE_HIGH (KERNEL_BASE_LOW + KERNEL_VIRT_OFFSET)
#define PHYSTOP_HIGH (PHYSTOP_LOW + KERNEL_VIRT_OFFSET)

#define NCPU 16

#endif
